import createNode from "./node.js";

export const __yyz_node = createNode;
export const __yyz_fragment = "fragment";

export const abs = (...args) => Math.abs.apply(Math, args);
export const acos = (...args) => Math.acos.apply(Math, args);
export const acosh = (...args) => Math.acosh.apply(Math, args);
export const asin = (...args) => Math.asin.apply(Math, args);
export const asinh = (...args) => Math.asinh.apply(Math, args);
export const atan = (...args) => Math.atan.apply(Math, args);
export const atanh = (...args) => Math.atanh.apply(Math, args);
export const atan2 = (...args) => Math.atan2.apply(Math, args);
export const ceil = (...args) => Math.ceil.apply(Math, args);
export const cbrt = (...args) => Math.cbrt.apply(Math, args);
export const expm1 = (...args) => Math.expm1.apply(Math, args);
export const clz32 = (...args) => Math.clz32.apply(Math, args);
export const cos = (...args) => Math.cos.apply(Math, args);
export const cosh = (...args) => Math.cosh.apply(Math, args);
export const exp = (...args) => Math.exp.apply(Math, args);
export const floor = (...args) => Math.floor.apply(Math, args);
export const fround = (...args) => Math.fround.apply(Math, args);
export const hypot = (...args) => Math.hypot.apply(Math, args);
export const imul = (...args) => Math.imul.apply(Math, args);
export const log = (...args) => Math.log.apply(Math, args);
export const log1p = (...args) => Math.log1p.apply(Math, args);
export const log2 = (...args) => Math.log2.apply(Math, args);
export const log10 = (...args) => Math.log10.apply(Math, args);
export const max = (...args) => Math.max.apply(Math, args);
export const min = (...args) => Math.min.apply(Math, args);
export const pow = (...args) => Math.pow.apply(Math, args);
export const random = (...args) => Math.random.apply(Math, args);
export const round = (...args) => Math.round.apply(Math, args);
export const sign = (...args) => Math.sign.apply(Math, args);
export const sin = (...args) => Math.sin.apply(Math, args);
export const sinh = (...args) => Math.sinh.apply(Math, args);
export const sqrt = (...args) => Math.sqrt.apply(Math, args);
export const tan = (...args) => Math.tan.apply(Math, args);
export const tanh = (...args) => Math.tanh.apply(Math, args);
export const trunc = (...args) => Math.trunc.apply(Math, args);
export const E = Math.E;
export const LN10 = Math.LN10;
export const LN2 = Math.LN2;
export const LOG10E = Math.LOG10E;
export const LOG2E = Math.LOG2E;
export const PI = Math.PI;
export const SQRT1_2 = Math.SQRT1_2;
export const SQRT2 = Math.SQRT2;
